/*
 *  workflow - A collaborative real-time white- and kanban board
 *  Copyright (C) 2018 Mark-André Hopf <mhopf@mark13.org>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

valuetype User {
    public unsigned long uid;
    public string name;
    public string password;
    public string email;
    public string fullname;
    public string avatar;
};

valuetype Point {
    public double x, y;
};

valuetype Size {
    public double width, height;
};

native SVGElement;
native Point;
native Figure_ptr;

valuetype Figure {
    public unsigned long id;
    SVGElement createSVG();
    double distance(in Point point);
};

valuetype Rectangle: Figure {
    public Point origin;
    public Size size;
};

valuetype FigureModel {
    public sequence<Figure> data;
};

valuetype Layer: FigureModel {
    public unsigned long id;
    public string name;
    Figure_ptr findFigureAt(in Point point);
};

valuetype Project {
    public unsigned long id;
    public string name;
    public string description;
};

valuetype Board {
    public unsigned long id;
    public string name;
    public string description;
    public sequence<Layer> layers;
};

valuetype Card {
    public unsigned long id;
    public string name;
    public string description;
};

interface Server {
    oneway void init(in string session);
    oneway void logon(in string user, in string password, in boolean remember);
};

interface Client {
    oneway void logonScreen(in unsigned long lifetime, in string disclaimer, in boolean remember, in string errorMessage);
    oneway void homeScreen(
    	in string cookie,
	in string avatar,
	in string email,
	in string fullname,
	in Board board);
};
